---
apiVersion: v1
kind: Namespace
metadata:
  namespace: kong-gatewayapi
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: kong-gatewayclass
spec:
  controller: kong
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata:
  name: kong-gateway
  namespace: kong-gatewayapi
spec:
  gatewayClassName: kong-gatewayclass
  listeners:
    - protocol: HTTP
      port: 80
      routes:
        kind: HTTPRoute
        selector:
          matchLabels:
            app: kuard
