apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kongclusterplugins.configuration.konghq.com
spec:
  group: configuration.konghq.com
  scope: Cluster
  names:
    kind: KongClusterPlugin
    listKind: KongClusterPluginList
    plural: kongclusterplugins
    shortNames:
    - kcp
    singular: kongclusterplugin
  versions:
  - additionalPrinterColumns:
    - description: Name of the plugin
      jsonPath: .plugin
      name: Plugin-Type
      type: string
    - description: Age
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: Indicates if the plugin is disabled
      jsonPath: .disabled
      name: Disabled
      priority: 1
      type: boolean
    - description: Configuration of the plugin
      jsonPath: .config
      name: Config
      priority: 1
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          config:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          configFrom:
            properties:
              secretKeyRef:
                properties:
                  key:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                - namespace
                - key
                type: object
            type: object
          disabled:
            type: boolean
          plugin:
            type: string
          protocols:
            items:
              enum:
              - http
              - https
              - grpc
              - grpcs
              - tcp
              - tls
              - udp
              type: string
            type: array
          run_on:
            enum:
            - first
            - second
            - all
            type: string
        required:
        - plugin
    served: true
    storage: true
    subresources:
      status: {}
  preserveUnknownFields: false
