apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kongconsumers.configuration.konghq.com
spec:
  group: configuration.konghq.com
  scope: Namespaced
  names:
    kind: KongConsumer
    listKind: KongConsumerList
    plural: kongconsumers
    shortNames:
    - kc
    singular: kongconsumer
  versions:
  - name: v1
    additionalPrinterColumns:
    - description: Username of a Kong Consumer
      jsonPath: .username
      name: Username
      type: string
    - description: Age
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    schema:
      openAPIV3Schema:
        type: object
        properties:
          credentials:
            items:
              type: string
            type: array
          custom_id:
            type: string
          username:
            type: string
    served: true
    storage: true
    subresources:
      status: {}
  conversion:
    strategy: None
  preserveUnknownFields: false
